# Chapter 4: Numpy Basics: Arrays and Vectorized Computation
## timeit:
- `%%time`: time the whole cell in Jupyter Notebook
- `%time`: time a single line in Jupyter Notebook
## Creating arrays:
- `np.arange(15)`: create an array of integers from 0 to 14.
- `data = np.random.randn(2, 3)`: generate a 2x3 array of random numbers from the standard normal distribution.
    - `data.shape`: returns the shape of the array (2, 3)
    - `data.dtype`: returns the data type of the array (float64)
    - `data.ndim`: returns the number of dimensions of the array (2)
    - `data.size`: returns the total number of elements in the array (6)
- `np.zeros((2, 3))`: creates a 2x3 array with zeros.
- `np.ones((2, 3))`: creates a 2x3 array with ones.
- `np.empty((2, 3))`: creates a 2x3 array sometimes containing garbage values or zeros. 
- `np.eye(2)`: creates a 2x2 identity matrix.

- `np.array([1, 2, 3], dtype=np.float64/np.int32)`: np.float64 means float 64-bit. bit means the number of bits used to store the data. The bigger the bit, the more precise the data can be. 

## Arithmetic operations on arrays apply ELEMENTWISE.
- between arrays of the same shape use `+`, `-`, `*`, `/` operators.
    - also `arr1 > arr2` will return an array of booleans. 
- for an array and a scalar use `*`, `/`  `**` operators.

## Sliceing and indexing:

- Basic indexing and slicing:
    - `arr[5]`: returns the 6th element of the array (index starts from 0).
    - `arr[5:8]`: returns a slice of the array from index 5 to index 7 (8 is not included). So 8-5 = 3 elements are returned.
    - `arr[:]`: all elements of the array.
    - `arr[5:8] = 12`: assigns the value 12 to the slice arr[5:8].
    - `arr_slice = arr[3:5]`: creates a VIEW of the array from index 3 to index 4 (5 is not included). Any changes in the slice will be reflected in the original array. This is called a view, not a copy.  
    - `arr_copy = arr[3:5].copy()`: creates a COPY of the array.
    - NOTE that `x=arr[3]` is a copy and `x = arr[3:4]` is a view. 

- arr.reshape() for one dimention arr, .reshape() returns an array containing the same data with a new shape.

- Multidimensional arrays:
    - `arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])`: creates a 2D array with 3 rows and 3 columns.
    - `arr2d[0]`: returns the first row of the array.
    - `arr2d[0][2]` or `arr2d[0, 2]`: returns the element in the first row and third column (index starts from 0).
    - `arr2d[:2]`: returns the first two rows of the array.
    - `arr2d[:1, :2]`: returns the first row and the first two columns of the array, keeping the dimensions of the array (2D array with one row and two columns).
    - `arr2d[0, :2]`: returns the first row and the first two columns of the array, but this will return a 1D array with two elements.

- Boolean indexing:
    - `names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])`: creates an array of strings.
    - `names == 'Bob'`: returns a boolean array indicating which elements are equal to 'Bob'.
    - `names[names == 'Bob']`: returns an array of elements that are equal to 'Bob  
    - `names[(names == 'Bob') | (names == 'Will')]`: returns an array of elements that are equal to 'Bob' or 'Will'.
    - `names[(names == 'Bob') & (names == 'Will')]`: returns an array of elements that are equal to 'Bob' and 'Will' (this will return an empty array because no element can be both 'Bob' and 'Will').
    - `~(names == 'Bob')`: returns an array of elements that are NOT equal to 'Bob'.  
- Fancy indexing:
    - `arr34 = np.array([[1,2,3],[4,5,6],[7,8,9]])`: creates a 2D array with 3 rows and 3 columns.
    - `arr34[[0,1,2],[0,1,2]]`: returns the elements at the specified row and column indices (1, 5, 9).
    - `arr34[[0,0,0],[1,2,3]]`: returns the elements at the specified row and column indices (2, 3, 4). Note that the column index 3 is out of bounds, so this will raise an IndexError.
    - `arr34[[0,1,2]][:, [0,1,2]]`: returns the elements at the specified row and column indices (1, 5, 9). This is equivalent to `arr34[[0,1,2],[0,1,2]]`.
- Transposing arrays and swapping axes:
    - `arr = np.arange(15).reshape((3,5))`: creates a 2D array with 3 rows and 5 columns.
    - `arr.T`: returns the transpose of the array, which is a view of the original array. The rows and columns are swapped. So the resulting array will have 5 rows and 3 columns.
    - `arr.swapaxes(0, 1)`: returns a view of the array with the specified axes swapped. In this case, it will swap the first and second axes, resulting in an array with 5 rows and 3 columns. This is equivalent to `arr.T` for a 2D array.




## Numpy is more efficient than Python lists for numerical operations.

In [ ]:
# Numpy is more efficient than Python lists for numerical operations.
import numpy as np

In [39]:
print("\nNumpy array multiplication:")
my_arr = np.arange(1000000)
%time for _ in range(10): my_arr = my_arr * 2 

print("\nPython list multiplication:")
my_list = list(range(1000000))
%time for _ in range(10): my_list = [x * 2 for x in my_list]


Numpy array multiplication:
CPU times: user 4.08 ms, sys: 20 μs, total: 4.1 ms
Wall time: 4.05 ms

Python list multiplication:
CPU times: user 132 ms, sys: 13.1 ms, total: 145 ms
Wall time: 149 ms


# 4.1. The NumPy ndarray: A Multidimensional Array Object
 - An ndarray is a multidimensional array of fixed-size items. 
 - batch operations on arrays are usually more efficient than Python loops.

In [55]:
import numpy as np

# Date generation using NumPy
## 2 rows, 3 columns random numbers from standard normal distribution
data = np.random.randn(2, 3) 

print(f"\nThe type of data is {type(data)}")
print(data)

print(f"\nThe shape of data is {data.shape}")
print(f"\nThe d(ata)type of data is {data.dtype}")


The type of data is <class 'numpy.ndarray'>
[[-0.71210194  0.77485974  0.81753236]
 [ 1.91365853 -0.49461961  0.38111297]]

The shape of data is (2, 3)

The d(ata)type of data is float64


In [45]:
# Arithmetic operations on arrays apply elementwise.
print(data * 10)
print(data + data)

[[ -5.19552263  -7.64421968   3.47388617]
 [  7.50570974  13.11884002 -12.27309355]]
[[-1.03910453 -1.52884394  0.69477723]
 [ 1.50114195  2.623768   -2.45461871]]


In [63]:
# Creating ndarrays
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)

# 2D array
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2)
print(f"Number of dimensions: {arr2.ndim}")
print(f"Shape of the array: {arr2.shape}")
print(f"Data type of the array: {arr2.dtype}")  

np.empty((2,3,4))

[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]
Number of dimensions: 2
Shape of the array: (2, 4)
Data type of the array: int64


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [72]:
arr = np.array([3.7, -1.2, 0, 10, 4.5])
print(arr)
print("Use arr.astype(np.int32) to convert the array to integers:")
print(arr.astype(np.int32))

[ 3.7 -1.2  0.  10.   4.5]
Use arr.astype(np.int32) to convert the array to integers:
[ 3 -1  0 10  4]


In [73]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings)
print(numeric_strings.astype(float))

[b'1.25' b'-9.6' b'42']
[ 1.25 -9.6  42.  ]


In [79]:
# comparing arraies

arr1 = np.array([[1., 2., 3.], [2., 1., 3.]])
arr2 = np.array([[0., 1., 2.], [3., 4., 5.]])
print(arr1)
print(arr2)
print("\nComparing arr1 > arr2 yields an array of booleans:\n")
print(arr1 > arr2)  

[[1. 2. 3.]
 [2. 1. 3.]]
[[0. 1. 2.]
 [3. 4. 5.]]

Comparing arr1 > arr2 yields an array of booleans:

[[ True  True  True]
 [False False False]]


## Indexing with slices:

In [90]:
# Basic indexing and slicing

arr =np.arange(10)
print(arr)

print(arr[5]) # start from 0, so arr[5] is the 6th element of the array

print(arr[5:8]) # slice from index 5 to index 7 (8 is not included). So 8-5 = 3 elements are returned.

arr[5:8] = 12 # assign the value 12 to the slice arr[5:8]
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [115]:
# any changse in the slice will be reflected in the original array. This is called a view, not a copy.
arr = np.arange(5)
print(f"The original array is: {arr}")
arr_slice = arr[3:5] # [:] will give assignment to all elements.
print(f"Make a view called arr_slice = arr[3:5]: {arr_slice}")
arr_slice[0] = 12345
print(f"Modified arr_slice[0]:{arr_slice}")
print(f"arr changes automatically, arr = : {arr}" )

# To get a copy of the array instead of a view. 
arr_copy = arr[:].copy()
print(f"Make a copy called arr_copy = arr[3:5].copy(): {arr_copy}")

The original array is: [0 1 2 3 4]
Make a view called arr_slice = arr[3:5]: [3 4]
Modified arr_slice[0]:[12345     4]
arr changes automatically, arr = : [    0     1     2 12345     4]
Make a copy called arr_copy = arr[3:5].copy(): [    0     1     2 12345     4]


In [107]:
# Higher dimensional arrays can have one index per axis.
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)
print(arr2d[2]) # the third row of the array
## The following are equivalent and will return the same value:
print(arr2d[0][2]) # the first row, third column of the array
print(arr2d[0, 2]) # the first row, third column of the array, this is equivalent to arr2d[0][2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
3
3


In [118]:
 # It is a copy not a view. So any changes to x will not affect arr1.
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr1)

x = arr1[0,0]
print(x)
x = 10
print(arr1)

print("\nThe above is a copy and the below is a view.\n")

# It is a view not a copy. So any changes to x will affect arr1.
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr1) 
x = arr1[0,0]
print(x)
arr1[0,0] = 10
print(arr1)

[[1. 2. 3.]
 [4. 5. 6.]]
1.0
[[1. 2. 3.]
 [4. 5. 6.]]

The above is a copy and the below is a view.

[[1. 2. 3.]
 [4. 5. 6.]]
1.0
[[10.  2.  3.]
 [ 4.  5.  6.]]


In [122]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr3d)
print("\n")
print(arr3d[0]) # the first 2D array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[1 2 3]
 [4 5 6]]


In [ ]:
# use scalar values in higher dimensional arrays will broadcast the scalar value to all elements in the array.

arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)
print(arr3d[0]) # the first 2D array

old_value = arr3d[0].copy() # make a copy of the first 2D array
arr3d[0] = 0
print(arr3d)

arr3d[0] = old_value
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[[ 0  0  0]
  [ 0  0  0]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Slicing in higher dimensional arrays
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print("arr2d[:2] the first two rows of the array:")
print(arr2d[:2]) # the first two rows of the array

print("Select the first row and the first 2 columns arr2d[:1, :2]:")
print(arr2d[:1, :2]) # keep the dimensions of the array, so the result is a 2D array with one row and two columns. I
print(arr2d[0, :2]) # the first row, first two columns of the array, this will return a 1D array with two elements.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[:2] the first two rows of the array:
[[1 2 3]
 [4 5 6]]
Select the first row and the first 2 columns arr2d[:1, :2]:
[[1 2]]
[1 2]


In [174]:
# Boolean indexing
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
print("\nBoolean indexing: names == 'Bob' will return a boolean array indicating which elements of names are equal to 'Bob':")
print(names == 'Bob')
print("\nUse this boolean array to select the rows of data where the name is 'Bob  :")
print(data[names == 'Bob'])

# Selecting data from an array by boolean indexing will always return a copy of the data, not a view. 
print("\nSelecting data by boolean indexing will always return a copy of the data, not a view.")
data_bob = data[names == 'Bob']
data_bob[:] = 0
print(data_bob)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-2.39274581  0.40196421  0.20617706 -0.26537466]
 [ 2.16553319  0.30591941 -0.08011769 -0.89987379]
 [-0.56900413  0.27177257  0.59493562 -0.63966865]
 [-2.36683268 -0.60782867 -1.70975042  0.24156167]
 [-0.86882244 -0.5409103   0.01017797  0.30484543]
 [ 1.00842631  0.34768769 -1.04525771 -0.11608968]
 [ 0.02452297 -1.93821817 -1.04873728  0.30038677]]

Boolean indexing: names == 'Bob' will return a boolean array indicating which elements of names are equal to 'Bob':
[ True False False  True False False False]

Use this boolean array to select the rows of data where the name is 'Bob  :
[[-2.39274581  0.40196421  0.20617706 -0.26537466]
 [-2.36683268 -0.60782867 -1.70975042  0.24156167]]

Selecting data by boolean indexing will always return a copy of the data, not a view.
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[-2.39274581  0.40196421  0.20617706 -0.26537466]
 [ 2.16553319  0.30591941 -0.08011769 -0.89987379]
 [-0.56900413  0.27177257  0.594935

In [177]:
a = data[data<0] 
a[:] = 0
print(data)

[[-2.39274581  0.40196421  0.20617706 -0.26537466]
 [ 2.16553319  0.30591941 -0.08011769 -0.89987379]
 [-0.56900413  0.27177257  0.59493562 -0.63966865]
 [-2.36683268 -0.60782867 -1.70975042  0.24156167]
 [-0.86882244 -0.5409103   0.01017797  0.30484543]
 [ 1.00842631  0.34768769 -1.04525771 -0.11608968]
 [ 0.02452297 -1.93821817 -1.04873728  0.30038677]]


In [172]:
# logic: and or negation by & | ~
print("\nLogic: and or negation by & | ~")
print(f"\t\t{names}")

print(f" Bob or Will: {(names == 'Bob') | (names == 'Will')}") 
print(f" Bob and Will: {(names == 'Bob') & (names == 'Will')}") 
print(f" Not Bob: {~(names == 'Bob')}") 


Logic: and or negation by & | ~
		['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
 Bob or Will: [ True False  True  True  True False False]
 Bob and Will: [False False False False False False False]
 Not Bob: [False  True  True False  True  True  True]


In [ ]:
# Fancy indexing allows you to select arbitrary rows or columns of an array using integers or boolean arrays.

## arr.reshape() for one dimention arr, .reshape() returns an array containing the same data with a new shape.
arr = np.arange(12)
print(arr)
arr34 = arr.reshape(3, 4)
print(arr34)

# To select a single element from a 2D array, you can pass a list of row and column indices to the array:
print(arr34[[0,1,2],[0,1,2]])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  5 10]


In [ ]:
# Fancy indexing. Always copy the date to a new array. 

arr = np.empty((8,4))

for i in range(8):
    arr[i] = i
print(arr)

print(arr[[4,3,0,6]]) # select the 5th, 4th, 1st, and 7th rows of the array in that order.

print(arr[[1,3,5,7],[0,3,1,2]]) # select the elements at the specified row and column indices. So it will select the element at row 1 and column 0, the element at row 3 and column 3, the element at row 5 and column 1, and the element at row 7 and column 2.

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
[1. 3. 5. 7.]


In [186]:
# Transporing arrays and swapping axes. 
## This returns a view. 

arr = np.arange(15).reshape((3,5))
print(arr)
print(arr.T) # Transpose of the array, which is a view of the original array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [192]:
# Transposing in higher dimensions is just a matter of reordering the axes, so you can transpose a 3D array by simply calling its transpose method with a tuple of axis numbers indicating the new order of the axes:

arr = np.arange(16).reshape((2,2,4))
print(arr)


print(arr.transpose((1,0,2))) # second axis first, first axis second, third axis unchanged.

print(arr.swapaxes(1,2)) # swap the second and third axes. This is equivalent to arr.transpose((0,2,1))



[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
